import type { Event } from "@/types/event-types";
import { daysFromNow } from "@/lib/utils";
import { thisWeekend } from "@/lib/utils";


export const MOCK_EVENTS: Event[] = [
  {
    id: "1",
    title: "Afrobeats Night Market",
    category: "Concerts",
    subcategory: "Afrobeats",
    venue: "Muri Okunola Park",
    city: "Victoria Island",
    state: "Lagos",
    no:"0210",
    createdAt: daysFromNow(0, 18),
    minPrice: 15_000,
    coverImage: "https://picsum.photos/seed/afrobeats/600/450",
    promotion: true,
    trendingScore: 98,
  },
  {
    id: "2",
    title: "Amapiano All Night",
    category: "Parties",
    venue: "Hard Rock Cafe",
    city: "Victoria Island",
    state: "Lagos",
     no:"0210",
    createdAt: daysFromNow(0, 22),
    minPrice: 8_000,
    coverImage: "https://picsum.photos/seed/amapiano/600/450",
    promotion: false,
    trendingScore: 91,
  },
  {
    id: "3",
    title: "Jos Plateau Jazz Evening",
    category: "Concerts",
    subcategory: "Jazz",
    venue: "Hill Station Hotel",
    city: "Jos",
    state: "Plateau",
      no:"0210",
    createdAt: daysFromNow(0, 19),
    minPrice: 0,
    coverImage: "https://picsum.photos/seed/jazz/600/450",
    promotion: false,
    trendingScore: 61,
  },

  {
    id: "4",
    title: "Sunset Rooftop Party",
    category: "Parties",
    venue: "Eko Hotel",
    city: "Victoria Island",
    state: "Lagos",
    no:"0210",
    createdAt: thisWeekend(17),
    minPrice: 12_500,
    coverImage: "https://picsum.photos/seed/rooftop/600/450",
    promotion: false,
    trendingScore: 88,
  },
  {
    id: "5",
    title: "Calabar Carnival",
    category: "Arts & Theatre",
    venue: "Cultural Centre",
    city: "Calabar",
    state: "Cross River",
    no:"0210",
    createdAt: thisWeekend(16),
    minPrice: 3_000,
    coverImage: "https://picsum.photos/seed/carnival/600/450",
    promotion: false,
    trendingScore: 84,
  },
  {
    id: "6",
    title: "Detty December Party",
    category: "Parties",
    venue: "Five Cowries Terminal",
    city: "Ikoyi",
    state: "Lagos",
    no:"0210",
    createdAt: thisWeekend(22),
    minPrice: 25_000,
    coverImage: "https://picsum.photos/seed/boat/600/450",
    promotion: false,
    trendingScore: 86,
  },

  {
    id: "7",
    title: "Abuja Tech Week",
    category: "Conferences",
    subcategory: "Tech",
    venue: "Transcorp Hilton",
    city: "Maitama",
    state: "FCT - Abuja",
    no:"0210",
    createdAt: daysFromNow(4, 9),
    minPrice: 45_000,
    coverImage: "https://picsum.photos/seed/techweek/600/450",
    promotion: false,
    trendingScore: 80,
  },
  {
    id: "8",
    title: "Comedy Central Live",
    category: "Comedy",
    venue: "Genesis Centre",
    city: "Port Harcourt",
    state: "Rivers",
    no:"0210",
    createdAt: daysFromNow(6, 20),
    minPrice: 5_000,
    coverImage: "https://picsum.photos/seed/comedy/600/450",
    promotion: false,
    trendingScore: 76,
  },
  {
    id: "9",
    title: "Kano Startup Mixer",
    category: "Tech",
    venue: "Kano Innovation Hub",
    city: "Kano",
    state: "Kano",
    no:"0210",
    createdAt: daysFromNow(5, 16),
    minPrice: 0,
    coverImage: "https://picsum.photos/seed/startup/600/450",
    promotion: false,
    trendingScore: 70,
  },

 
  {
    id: "10",
    title: "Lagos Jollof Festival",
    category: "Food & Drink",
    venue: "Landmark Beach",
    city: "Oniru",
    state: "Lagos",
    no:"0210",
    createdAt: daysFromNow(15, 12),
    minPrice: 0,
    coverImage: "https://picsum.photos/seed/jollof/600/450",
    promotion: false,
    trendingScore: 74,
  },
  {
    id: "11",
    title: "High Life and Chill",
    category: "Parties",
    venue: "Ojez Restaurant",
    city: "Surulere",
    state: "Lagos",
    no:"0210",
    createdAt: daysFromNow(18, 21),
    minPrice: 3_000,
    coverImage: "https://picsum.photos/seed/highlife/600/450",
    promotion: false,
    trendingScore: 68,
  },
  {
    id: "12",
    title: "Enugu Coal City Marathon",
    category: "Sports",
    subcategory: "Athletics",
    venue: "Nnamdi Azikiwe Stadium",
    city: "Enugu",
    state: "Enugu",
    no:"0210",
    createdAt: daysFromNow(21, 7),
    minPrice: 2_500,
    coverImage: "https://picsum.photos/seed/marathon/600/450",
    promotion: false,
    trendingScore: 66,
  },
  {
    id: "13",
    title: "Ibadan Book & Arts Fair",
    category: "Arts & Theatre",
    venue: "Cultural Centre Mokola",
    city: "Ibadan",
    state: "Oyo",
    no:"0210",
    createdAt: daysFromNow(24, 10),
    minPrice: 1_500,
    coverImage: "https://picsum.photos/seed/bookfair/600/450",
    promotion: false,
    trendingScore: 58,
  },
  {
    id: "14",
    title: "Sunday League Final",
    category: "Sports",
    subcategory: "Football",
    venue: "Lekan Salami Stadium",
    city: "Ibadan",
    state: "Oyo",
    no:"0210",
    createdAt: daysFromNow(45, 16),
    minPrice: 2_000,
    coverImage: "https://picsum.photos/seed/football/600/450",
    promotion: false,
    trendingScore: 64,
  },
  {
    id: "15",
    title: "Kaduna Food Festival",
    category: "Food & Drink",
    venue: "Murtala Square",
    city: "Kaduna",
    state: "Kaduna",
    no:"0210",
    createdAt: daysFromNow(52, 11),
    minPrice: 0,
    coverImage: "https://picsum.photos/seed/kadunafood/600/450",
    promotion: false,
    trendingScore: 55,
  },
  {
    id: "16",
    title: "Benin Bronze Exhibition",
    category: "Arts & Theatre",
    venue: "National Museum",
    city: "Benin City",
    state: "Edo",
    no:"0210",
    createdAt: daysFromNow(60, 10),
    minPrice: 18_000,
    coverImage: "https://picsum.photos/seed/bronze/600/450",
    promotion: false,
    trendingScore: 52,
  },
];